const products = [
  {
    name: 'Call of Duty: Modern Warfare',
    genres: [
      'FPS',
      'Shooter',
      'Multiplayer',
      'Action',
    ],
    price: 59.99,
    publisher: 'Activision',
    description: 'Conquiste Todas as Frentes. Lute em batalhas aéreas sobre o Pacífico, salte de paraquedas na França, defenda o Stalingrado com um fuzil de precisão e prossiga em meio a forças avançando no norte da África. A franquia Call of Duty® franchise returna com Call of Duty®: Vanguard, desenvolvido pela Sledgehammer Games onde jogadores serão imersos no combate visceral da 2ª Guerra em uma escala global sem precedente.',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202108/1103/HRv1ZLEnsIQ2joLUpKTIfeWK.png?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/img/rnd/202109/2218/Ri3UdNJfXpiv6bGxmFaVG00M.png?w=620&thumb=false',
    numberOfPlayers: 2,
    multiplayerPlayers: 48,
    quantity: 0,
    featured: true,
  },
  {
    name: 'Saints Row Gold Edition',
    genres: [
      'FPS',
      'Shooter',
      'Multiplayer',
      'Action',
    ],
    price: 59.99,
    publisher: 'Deep Silver',
    description: 'Neenah, Kevin e Eli apontam você como Chefe e formam os Saints para que, juntos, vocês encarem Los Panteros, os Idols e a Marshall enquanto erguem seu império e lutam pelo controle da cidade. No fundo, Saints Row é a história de uma startup, só acontece que o negócio dos Saints é o crime.',
    releaseDate: '12-12-2020',
    rate: 5,
    heroImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202108/0913/mwv09SYpsTJxjEBXS0qwCKHi.png?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/ap/rnd/202108/0913/C8euJVij7m20ePHVXr9DHwlg.png?w=230&thumb=false',
    numberOfPlayers: 2,
    multiplayerPlayers: 2,
    quantity: 5,
    featured: true,
  },
  {
    name: 'Forspoken',
    genres: [
      'RPG',
      'Action',
    ],
    price: 59.99,
    publisher: 'Square Enix',
    description: 'Forspoken conta a jornada de Frey, uma jovem nova-iorquina levada à bela e cruel Athia. Frey precisa usar suas habilidades mágicas recém-descobertas para explorar e enfrentar criaturas monstruosas em busca de um caminho de volta para casa.',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202111/2501/NQVGY5xwfNjXtTB9ktuIOXbx.jpg?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/ap/rnd/202111/2508/hp4r1tyHDidnDGxJbXExPyi6.png?w=230&thumb=false',
    numberOfPlayers: 2,
    multiplayerPlayers: 0,
    quantity: 5,
    featured: true,
  },
  {
    name: "Tiny Tina's Wonderlands",
    genres: [
      'FPS',
      'Shooter',
      'Multiplayer',
      'Action',
    ],
    price: 59.99,
    publisher: '2k',
    description: 'UM MUNDO FANTÁSTICO E IMPREVISÍVEL A Tiny Tina é sua guia anárquica num extraordinário reino de jogo de mesa quase sem regras. Explore um mundo vasto com cidades majestosas, sinistras florestas de cogumelos, fortalezas agourentas e muito mais!',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202108/0510/3sgX61lyRXK82Q7JVxKB8U3e.png?w=780&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/ap/rnd/202105/0718/2gh2zdt2MQCLWLGkB9HTPGmR.png?w=230&thumb=false',
    numberOfPlayers: 2,
    multiplayerPlayers: 0,
    quantity: 5,
    featured: false,
  },
  {
    name: 'Mortal Shell',
    genres: [
      'RPG',
      'Action',
    ],
    price: 124.99,
    publisher: 'PSN',
    description: 'Mortal Shell é um complexo RPG de ação implacável que testa a tua sanidade e resiliência num mundo despedaçado. Enquanto os restos da humanidade definham e apodrecem, inimigos zelosos deterioram-se nas ruínas. Eles não têm misericórdia e a sobrevivência irá exigir consciência, precisão e instintos superiores. Encontra santuários ocultos de seguidores devotos e descobre o teu verdadeiro propósito.',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/img/rnd/202011/2511/ZByjmAAlwXrsxrj5j1ji8IZk.png?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/ap/rnd/202008/0109/F5Wvzwr4VFVlonLj4wtjYkDx.png?w=440&thumb=false',
    numberOfPlayers: 1,
    multiplayerPlayers: 0,
    quantity: 5,
    featured: false,
  },
  {
    name: "Tom Clancy's Ghost Recon: Wildlands",
    genres: [
      'FPS',
      'Shooter',
      'Multiplayer',
      'Action',
    ],
    price: 59.99,
    publisher: 'Ubisoft',
    description: "Em Tom Clancy's Ghost Recon® Wildlands, o cartel de Santa Blanca transformou a linda Bolívia em um perigoso país do narcotráfico, levando-o à falta de leis, ao medo e à violência crescente. Com sua influência corrosiva crescente, o cartel está decidido a levar o país inteiro à ruína.",
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/img/rnd/202010/1322/1EGCeZ3vdXjJ73EaZagdKZUu.jpg?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/cdn/UP0001/CUSA02902_00/LmixBxp3eIPxu3vc1y4Bxx3UIc3l6rzx.png?w=230&thumb=false',
    numberOfPlayers: 1,
    multiplayerPlayers: 10,
    quantity: 4,
    featured: false,
  },
  {
    name: 'Re Reckoning',
    genres: [
      'RPG',
      'Action',
    ],
    price: 59.99,
    publisher: 'Ubisoft',
    description: 'O retorno do RPG de sucesso! Das mentes de R. A. Salvatore, autor best-seller; Todd McFarlane, criador de Spawn; e Ken Rolston, designer chefe de Elder Scrolls IV: Oblivion, chega Kingdoms of Amalur: Re-Reckoning. Remasterizado com visuais deslumbrantes e jogabilidade refinada, Re-Reckoning proporciona um intenso combate de RPG personalizável dentro de um mundo imenso. Descubra os segredos de Amalur, da cidade vibrante de Rathir à vasta região de Dalentarth às masmorras nefastas de Brigand Hall Caverns. Salve um mundo destruído por uma guerra brutal e controle as chaves da imortalidade como o primeiro guerreiro a ressurgir das garras da morte.',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/img/rnd/202011/0204/3Qv8BYadCG9vOx8FqKAvmZea.png?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/ap/rnd/202006/2610/7j1GUXdvOGPoLaaQRt2J2viK.png?w=230&thumb=false',
    numberOfPlayers: 1,
    multiplayerPlayers: 0,
    quantity: 5,
    featured: false,
  },
  {
    name: 'Fifa 22',
    genres: [
      'Sports',
      'Soccer',
    ],
    price: 59.99,
    publisher: 'EA Sports',
    description: 'Jogue o FIFA 22 e ganhe um Item de Jogador de Próxima Geração: receba um Item de Jogador de Próxima Geração (não negociável) no FIFA Ultimate Team a partir de 15 de dezembro ao jogar o FIFA 22 até 14 de janeiro de 2022*.',
    releaseDate: '12-12-2020',
    rate: 4.5,
    heroImage: 'https://image.api.playstation.com/vulcan/img/rnd/202111/0822/8wW1e7X2lNVqTIvogyo4JngC.png?w=1920&thumb=false',
    thumb: 'https://image.api.playstation.com/vulcan/img/rnd/202111/0822/YiFF5Xkljek03HhUJa4gic1Y.png?w=440&thumb=false',
    numberOfPlayers: 1,
    multiplayerPlayers: 0,
    quantity: 5,
    featured: false,
  },
];

export default products;
